# Name of website
title: Exelvision

description: Retro Programmers United For Obsure Systems (RPUFOS), for Name of the OS.

# Leave blank for a user site or set "/project-name" for a project site
url: "https://VFD.github.io"

baseurl: "/Exelvision"

# Build settings
timezone: "Europe/Paris"

# Conversion
markdown: kramdown


# Exclude
exclude:
    - .vscode/
    - .github/



